# Generated by Django 5.1.15 on 2026-09-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='mode',
            field=models.CharField(choices=[('dating', 'Знайомства'), ('bff', 'Пошук друзів')], max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('dating', 'Знайомства'), ('bff', 'Пошук друзів')], max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Спам'), ('harassment', 'Переслідування'), ('fake_profile', 'Фейковий профіль'), ('inappropriate_content', 'Неприйнятний контент'), ('other', 'Інше')], max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('resolved', 'Розглянуто'), ('dismissed', 'Відхилено')], default='pending', max_length=20),
        ),
    ]
