# Generated by Django 5.2.17 on 2026-09-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_like_mode_alter_match_mode_alter_report_reason_and_more'),
        ('meetings', '0001_meeting_models'),
        ('messaging', '0003_message_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='matching.match'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('match__isnull', False), ('meeting__isnull', True)), models.Q(('match__isnull', True), ('meeting__isnull', False)), _connector='OR'), name='conversation_exactly_one_owner'),
        ),
    ]
