# Generated by Django 5.1.15 on 2026-08-15 08:29

from django.db import migrations, models


def normalize_usernames(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(username='').update(username=None)

    seen = {}
    for user in User.objects.exclude(username__isnull=True).order_by('id'):
        key = user.username.lower()
        if key in seen:
            user.username = f'{user.username}_{user.pk}'
            user.save(update_fields=['username'])
        else:
            seen[key] = user.pk


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
