# Generated by Django 5.1.15 on 2026-08-01 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('other', 'Other')], max_length=20)),
                ('orientation', models.CharField(choices=[('straight', 'Straight'), ('gay', 'Gay'), ('bisexual', 'Bisexual'), ('other', 'Other')], max_length=20)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('active_mode', models.CharField(choices=[('dating', 'Dating'), ('bff', 'Friend Finder')], default='dating', max_length=10)),
                ('looking_for', models.CharField(blank=True, choices=[('male', 'Men'), ('female', 'Women'), ('everyone', 'Everyone')], max_length=20)),
                ('min_age', models.PositiveSmallIntegerField(default=18)),
                ('max_age', models.PositiveSmallIntegerField(default=99)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('interest', 'Interest'), ('language', 'Language'), ('hobby', 'Hobby'), ('activity', 'Activity')], max_length=20)),
            ],
            options={
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_tag_name_per_category')],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['profile', 'order'], name='profiles_ph_profile_ae3dc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tags', to='profiles.profile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tags', to='profiles.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['profile'], name='profiles_pr_profile_b47e07_idx'), models.Index(fields=['tag'], name='profiles_pr_tag_id_21af70_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'tag'), name='unique_profile_tag')],
            },
        ),
    ]
