# Generated by Django 5.1.15 on 2026-08-15 08:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


SEED_TAGS = {
    'interest': [
        'Музика',
        'Кіно',
        'Спорт',
        'Кулінарія',
        'Мистецтво',
        'Ігри',
        'Читання',
        'Фотографія',
        'Танці',
        'Волонтерство',
        'Тварини',
        'Подорожі',
        'Наука',
        'Фітнес',
    ],
    'hobby': [
        'Настільні ігри',
        'Походи',
        'Біг',
        'Йога',
        'Гітара',
        'Шахи',
        'Велоспорт',
        'Плавання',
        'Малювання',
        'Кулінарія',
    ],
    'language': [
        'Українська',
        'Англійська',
        'Польська',
        'Німецька',
        'Французька',
        'Іспанська',
        'Шведська',
    ],
}


def copy_profile_modes(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    ProfileMode = apps.get_model('profiles', 'ProfileMode')
    for profile in Profile.objects.all():
        ProfileMode.objects.get_or_create(
            profile=profile,
            mode='dating',
            defaults={
                'bio': getattr(profile, 'bio', '') or '',
                'looking_for': getattr(profile, 'looking_for', '') or '',
                'min_age': getattr(profile, 'min_age', 18) or 18,
                'max_age': getattr(profile, 'max_age', 99) or 99,
            },
        )
        ProfileMode.objects.get_or_create(
            profile=profile,
            mode='bff',
            defaults={'bio': '', 'looking_for': '', 'min_age': 18, 'max_age': 99},
        )


def seed_tags(apps, schema_editor):
    Tag = apps.get_model('profiles', 'Tag')
    for category, names in SEED_TAGS.items():
        for name in names:
            Tag.objects.get_or_create(name=name, category=category)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('dating', 'Dating'), ('bff', 'Друзі')], max_length=10)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('looking_for', models.CharField(blank=True, max_length=20)),
                ('min_age', models.PositiveSmallIntegerField(default=18)),
                ('max_age', models.PositiveSmallIntegerField(default=99)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='profiles.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='profilemode',
            constraint=models.UniqueConstraint(fields=('profile', 'mode'), name='unique_profile_mode'),
        ),
        migrations.RunPython(copy_profile_modes, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='profiletag',
            name='unique_profile_tag',
        ),
        migrations.RemoveIndex(
            model_name='profiletag',
            name='profiles_pr_profile_b47e07_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='looking_for',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='min_age',
        ),
        migrations.AddField(
            model_name='profile',
            name='children',
            field=models.CharField(blank=True, choices=[('no', 'Немає'), ('have', 'Є діти'), ('want', 'Хочу дітей'), ('unsure', 'Поки не знаю')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(230)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_discoverable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoking',
            field=models.CharField(blank=True, choices=[('no', 'Не курю'), ('sometimes', 'Інколи'), ('yes', 'Курю')], max_length=20),
        ),
        migrations.AddField(
            model_name='profiletag',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profiletag',
            name='mode',
            field=models.CharField(choices=[('dating', 'Dating'), ('bff', 'Друзі')], default='dating', max_length=10),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active_mode',
            field=models.CharField(choices=[('dating', 'Dating'), ('bff', 'Друзі')], default='dating', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Чоловік'), ('female', 'Жінка'), ('non_binary', 'Небінарний'), ('other', 'Інше')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orientation',
            field=models.CharField(choices=[('straight', 'Гетеро'), ('gay', 'Гей / лесбійка'), ('bisexual', 'Бісексуал'), ('other', 'Інше')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='profiletag',
            index=models.Index(fields=['profile', 'mode'], name='profiles_pr_profile_fd465f_idx'),
        ),
        migrations.AddConstraint(
            model_name='profiletag',
            constraint=models.UniqueConstraint(fields=('profile', 'tag', 'mode'), name='unique_profile_tag_per_mode'),
        ),
        migrations.RunPython(seed_tags, migrations.RunPython.noop),
    ]
