# Generated by Django 5.1.15 on 2026-09-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_dual_mode_profile_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерації'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active_mode',
            field=models.CharField(choices=[('dating', 'Знайомства'), ('bff', 'Пошук друзів')], default='dating', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерації'), ('approved', 'Схвалено'), ('suspended', 'Призупинено')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilemode',
            name='mode',
            field=models.CharField(choices=[('dating', 'Знайомства'), ('bff', 'Пошук друзів')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profiletag',
            name='mode',
            field=models.CharField(choices=[('dating', 'Знайомства'), ('bff', 'Пошук друзів')], default='dating', max_length=10),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('interest', 'Інтерес'), ('language', 'Мова'), ('hobby', 'Хобі')], max_length=20),
        ),
    ]
