# Generated by Django 5.1.15 on 2026-09-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_photo_status_alter_profile_active_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('no', "Не п'ю"), ('sometimes', 'Інколи'), ('yes', 'Часто')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='pets',
            field=models.CharField(blank=True, choices=[('no', 'Немає'), ('have', 'Є домашні тварини')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='sport',
            field=models.CharField(blank=True, choices=[('no', 'Не займаюсь'), ('sometimes', 'Інколи'), ('yes', 'Часто')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='zodiac_sign',
            field=models.CharField(blank=True, choices=[('aries', 'Овен'), ('taurus', 'Телець'), ('gemini', 'Близнюки'), ('cancer', 'Рак'), ('leo', 'Лев'), ('virgo', 'Діва'), ('libra', 'Терези'), ('scorpio', 'Скорпіон'), ('sagittarius', 'Стрілець'), ('capricorn', 'Козерог'), ('aquarius', 'Водолій'), ('pisces', 'Риби')], max_length=20),
        ),
    ]
