# Generated by Django 5.1.15 on 2026-09-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_alcohol_profile_pets_profile_sport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemode',
            name='age_preference',
            field=models.CharField(blank=True, choices=[('no_limit', 'Без обмежень'), ('peers', 'Однолітки')], max_length=20),
        ),
        migrations.AddField(
            model_name='profilemode',
            name='alcohol_attitude',
            field=models.CharField(blank=True, choices=[('negative', 'Негативне'), ('neutral', 'Нейтральне'), ('positive', 'Позитивне')], max_length=20),
        ),
        migrations.AddField(
            model_name='profilemode',
            name='meeting_format',
            field=models.CharField(blank=True, choices=[('in_person', 'Особисті зустрічі'), ('online', 'Спілкування онлайн'), ('both', 'Обидва варіанти')], max_length=20),
        ),
        migrations.AddField(
            model_name='profilemode',
            name='relationship_goal',
            field=models.CharField(blank=True, choices=[('serious', 'Серйозні стосунки'), ('dating', 'Побачення та флірт'), ('casual', 'Вільні стосунки')], max_length=20),
        ),
        migrations.AddField(
            model_name='profilemode',
            name='smoking_attitude',
            field=models.CharField(blank=True, choices=[('negative', 'Негативне'), ('neutral', 'Нейтральне'), ('positive', 'Позитивне')], max_length=20),
        ),
    ]
