# Generated by Django 5.1.15 on 2026-09-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_seed_bff_hobby_language_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemode',
            name='looking_for',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
